name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Learning Github Lab User"
          secondGreeting: "MD ARIFUL HAQUE Learning Lab User"
          thirdGreeting: "SHAMIM Learning Lab User"
